### ISSUE TITLE
GTF files

### ISSUE THREAD

**Issue by IsaacPonce** [mandricigor/isoem-bootstrap#2]
Hi, I think the program cannot read my gtf file, when i run isoem2 I got:
`Parsing GTF file...
Found 0 isoforms and 0 genes`
and the output folder is empty
my gtf format is:
1	GRCh38.87anno	gene	28736	29810	0	+	.	gene_id "CpG_116_1"; transcript_id "CpG_116_1";
I guess it is the correct gtf format, I compared with the gtf example given and it is equal, I tried change the feature to "exon" but same error happen. Thank you in advance.

**Comment by mandricigor** [comment]
Hi Isaac,

Can you please provide me your GTF file so I can work on this issue?

THanks

**Comment by IsaacPonce** [comment]
Thank you for your attention, I just changed the ":" in the description column for a normal character and it worked. Great program
